name=WaktuLokal
version=1.1.1
author=Ahmad AlBrabasi & Developer JWS
maintainer=Developer JWS
sentence=Library Hijriah Kuwaiti dan Pasaran Jawa untuk Jam Waktu Sholat.
paragraph=Menyediakan perhitungan penanggalan Hijriah presisi dan Pasaran Jawa dengan fitur koreksi mandiri dan auto-Maghrib.
category=Timing
url=https://github.com/albrabasi/JWS_HijriyahDanPasaran
architectures=esp32
